config/routes.rb
Rails.application.routes.draw do
  root :to => 'shops#index'
  resources 'shops'
  post 'shops/show_now_open'
  post 'shops/search'
  post 'shops/edit_categories'
  post 'shops/update_categories'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories_owned_by_shop.rb
class CategoriesOwnedByShop < ApplicationRecord
  has_many :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categories_owned_by_shop
end

app/models/category_other.rb
class CategoryOther < ApplicationRecord
  belongs_to :shop
end

app/models/record.rb
class Record < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :categories_owned_by_shop

  validates_uniqueness_of :name, scope: :place_id, message: "すでに登録されています"
end

app/models/user.rb
class User < ApplicationRecord
  devise :omniauthable, :omniauth_providers => [:twitter, :facebook]

  def self.find_or_create_from_oauth(auth)
    user = where(uid: auth.uid, provider: auth.provider).first_or_create do |user|
      user.user_name = auth.info.name
      user.avatar_url = auth.info.image
    end
    if user.user_name != auth.info.name
      user.update(username: auth.info.name)
    end
    if user.avatar_url = auth.info.image
      user.update(avatar_url: auth.info.image)
    end
    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  before_action :get_week, only: [:show_now_open, :show]
  before_action :get_api_key, only: [:new, :show]
  before_action :instanciate_api_place_details_client, except: [:index, :new]
  before_action :get_shop_details, only: [:show, :edit_categories]
  before_action :authenticate_user!, only: [:new]

  def index

  end

  def new
    @shop = Shop.new
  end

  def show
    shop_id = params[:shop_id]
    get_categories(shop_id)
    get_category_others(shop_id)
  end

  def search
    shop_name = params[:name] + " つくば"
    @api_place_search_client = TsukubaMesinavi::Api::ApiPlaceSearchClient.new
    @shops = @api_place_search_client.request_place_search_to_obj(TsukubaMesinavi::Entity::RequestPlaceSearch.new(shop_name))
    @lat = @shops.first.lat
    @lng = @shops.first.lng
    @shop = Shop.new(name: @shops.first.name)
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      shop_api = @api_place_details_client.request_place_details_to_obj(TsukubaMesinavi::Entity::RequestPlaceDetails.new(@shop.id, @shop.place_id))
      redirect_to shop_path(@shop.id, shop_id: @shop.id, place_id: @shop.place_id, lat: shop_api.lat, lng: shop_api.lng, registed: true)
    else
      get_api_key
      render :new
    end
  end

  def show_now_open
    @shops = []
    @shops_unknown = []
    Shop.all.each do |shop_from_db|
      shop = @api_place_details_client.request_place_details_to_obj(TsukubaMesinavi::Entity::RequestPlaceDetails.new(shop_from_db.id, shop_from_db.place_id))
      if shop.present?
        if shop.opening_hours.nil?
          @shops_unknown.push(shop)
        elsif shop.opening_hours["open_now"]
          @shops.push(shop)
        end
      end
    end
    respond_to do |format|
      format.js
    end
  end

  def edit_categories
    shop_id = params[:shop_id]
    get_checked_categories(shop_id)
    get_category_others(shop_id)
    respond_to do |format|
      format.js
    end
  end

  def update_categories
    shop_id = params[:shop_id]
    categories = params[:categories]
    category_other = params[:category_other] if params.has_key?(:category_other)
    category_owned_by_shop = Array.new
    categories.each do |category|
      category_owned_by_shop.push({shop_id: shop_id, category_id: category})
    end
    CategoriesOwnedByShop.destroy_all(shop_id: shop_id)
    CategoryOther.destroy_all(shop_id: shop_id)
    CategoriesOwnedByShop.create(category_owned_by_shop)
    CategoryOther.create({shop_id: shop_id, name: category_other})
    get_categories(shop_id)
    get_category_others(shop_id)
    @message = "保存しました"
    respond_to do |format|
      format.js
    end
  end

  private
    def get_week
      wday = Date.today.wday - 1
      @week = wday != -1 ? wday : 6
    end

    def get_api_key
      @api_key = Rails.application.secrets.google_api_key
    end

    def instanciate_api_place_details_client
      @api_place_details_client = TsukubaMesinavi::Api::ApiPlaceDetailsClient.new
    end

    def get_shop_details
      @shop_api = @api_place_details_client.request_place_details_to_obj(TsukubaMesinavi::Entity::RequestPlaceDetails.new(params[:shop_id], params[:place_id]))
      @shop_info = Shop.where(place_id: params[:place_id]).to_a.shift
    end

    def get_categories(shop_id)
      @categories_owned_by_shop = Category.joins(:categories_owned_by_shop)
      .select("categories.id AS category_id, categories.name")
      .where("categories_owned_by_shops.shop_id = ?", shop_id)
    end

    def get_category_others(shop_id)
      @category_others = CategoryOther.where("shop_id = ?", shop_id)
    end

    def get_checked_categories(shop_id)
      @checked_categories = Array.new
      categories = Category.all
      categories_owned_by_shop = get_categories(shop_id)
      categories.each do |category|
        @checked_categories.push({category_id: category.id, name: category.name, checked: false, category_other: nil})
      end
      @checked_categories.map { |checked_category|
        categories_owned_by_shop.each do |category_owned_by_shop|
          checked = checked_category[:category_id] == category_owned_by_shop.category_id
          checked_category[:checked] = checked if checked
        end
      }
    end

    def shop_params
      params.require(:shop).permit(:name, :place_id)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    callback_from :twitter
  end

  def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)
    provider = provider.to_s
    @user = User.find_or_create_from_oauth(request.env['omniauth.auth'])
    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <p id="right">Copyright(c) TsukubaMesinavi 2017</p>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <%= link_to image_tag("logo.png", :id => "logo"), root_path %>
  <%unless user_signed_in? %>
    <div id="login_menu" class="dropdown">
      <button id="login" class="btn btn-default" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        ログイン
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" aria-labelledby="login">
        <li><%=link_to "Facebook", user_facebook_omniauth_authorize_path%></li>
        <li><%=link_to "Twitter", user_twitter_omniauth_authorize_path%></li>
      </ul>
    </div>
  <% else %>
  <div id="user" class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="user_menu" data-toggle="dropdown">
      <%=image_tag(current_user.avatar_url)%>
    </button>
    <ul class="dropdown-menu" aria-labelledby="user_menu">
      <li id="username"><%=current_user.user_name%></li>
      <li class="line"><%=link_to "ログアウト", destroy_user_session_path, {:method => "delete"}%></li>
    </ul>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>つくば飯ナビ</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag('assets/favicon.ico') %>
  </head>

  <body>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-56516134-4', 'auto');
      ga('send', 'pageview');
    </script>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shops/_categories.html.erb
<%@categories_owned_by_shop.each do |category|%>
  <%if category.category_id == 9%>
    <p><%= category.name %></p>
    <% @category_others.each do |category_other|%>
      <ul>
        <li><%= category_other.name %></li>
      </ul>
    <%end%>
  <% else %>
    <%= category.name %>
  <%end%>
<%end%>
<%if user_signed_in? %>
  <button id="edit_categories_button" class="btn btn-default">編集する</button>
<%end%>

app/views/shops/_category_other.html.erb
<!--div class="input-group"-->
  <%=text_field_tag :category_other ,'' ,class: 'form-control'%>
  <!--span class="input-group-btn">
    <button class="btn btn-default delete_btn" type="button">削除</button>
  </span-->
<!--/div-->

app/views/shops/_loading.html.erb
<div class="modal fade" id="loading">
  <div class="modal-dialog modal-lg modal-middle">
    <div class="modal-body">
      <%= image_tag("loading.gif", :size => "200×200") %>
    </div>
  </div>
</div>

app/views/shops/_now_open_shops.html.erb
<div class="shop_category page-header">
  <h1>開店しているお店</h1>
</div>
<div class="container">
  <div class="row">
    <% @shops.each do |shop| %>
      <%= link_to shop_path(shop.shop_id, shop_id:shop.shop_id, place_id: shop.place_id, lat: shop.lat, lng: shop.lng) do %>
        <div id="shop_container" class="col-md-2">
          <%= image_tag("ramen.jpg", :alt => "イメージ", :class => "shop_image img-thumbnail") %>
          <p class="shop_description shop_name"><%= shop.name %></p>
          <p class="shop_description shop_opening_hour"><%=shop.opening_hours["weekday_text"][@week]%></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shops/_search_result.html.erb
<td>候補</td>
<td>
  <%= form_for(@shop, url: {action: 'create'}) do |f|%>
    <%if @shop.errors.any?%>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    <%end%>
    <%= f.select :place_id, @shops.map{|shop| [shop.name, shop.place_id]}, {}, {class: 'form-control'}%>
    <%= f.hidden_field :name%>
    <%@shops.each do |shop|%>
      <%=hidden_field_tag shop.place_id, {lat: shop.lat, lng: shop.lng}.to_json %>
    <%end%>
    <%= f.submit("登録", {class: 'form-control', id: "submit_shop_info"})%>
  <%end%>
</td>

app/views/shops/_top.html.erb
<div class="container_fluid">
  <div id="introduction">
    <h1 class="intro_text">さあ、ご飯にしよう</h1>
    <p class="intro_text">つくば飯ナビはつくば市内で今開いている飲食店を探し出せるサービスです</p>
    <p class="intro_text">お腹を満たして、引き続き研究を頑張りましょう！！</p>
  </div>
</div>

app/views/shops/edit_categories.js.erb
$("#edit_categories").html('<%= j(render :partial => "edit_categories", :locals => {:categories => @categories, :categories_owned_by_shop => @categories_owned_by_shop}) %>');
$("#categories").hide();
initCategoryOther();

app/views/shops/index.html.erb
<%= render 'shops/top'%>
<div id="search_button">
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#loading">開店しているお店を探す</button>
  <%if user_signed_in?%>
    <%= link_to "お店追加", new_shop_path, {class: 'btn btn-info btn-lg'}%>
  <% end %>
</div>
<%= render partial: 'loading'%>

<div id="now_open_shop"></div>

app/views/shops/new.html.erb
<%= javascript_include_tag "maps/map" %>
<%= javascript_include_tag "maps/map_new" %>
<%= stylesheet_link_tag "map"%>
<%= render partial: 'top'%>
<div id="map" style="display:none"></div>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%=@api_key%>">
</script>
<div class="shop_category page-header">
  <h1>お店の登録</h1>
</div>
<div class="container">
  <table class="table">
    <tbody>
      <tr>
        <th></th>
        <th>
          <% if @shop.errors.any? %>
            <div class="alert alert-danger" role="alert">
              <%= @shop.errors.messages[:name].shift%>
            </div>
          <%end%>
        </th>
      </tr>
      <tr>
        <td>店舗名</td>
        <td id="shop_name_input">
          <div class="input-group">
            <%=text_field_tag :shop_name_text, '',class: 'form-control' %>
            <span class="input-group-btn">
              <button id="search" class="btn btn-default" type="button" disabled=true>検索</button>
            </span>
          </div>
        </td>
      </tr>
      <tr id="shop_candidate"></tr>
    </tbody>
  </table>
</div>
<%= render partial: 'loading'%>

app/views/shops/search.js.erb
var lat = <%= @lat%>
var lng = <%= @lng%>
$("#shop_candidate").html('<%= j(render :partial => "search_result", :locals => {:shops => @shops}) %>');
initMap(lat, lng);

app/views/shops/show.html.erb
<%= javascript_include_tag "maps/map" %>
<%= javascript_include_tag "maps/map_show" %>
<%= javascript_include_tag "shop_show"%>
<%= stylesheet_link_tag "map"%>
<div id="map"></div>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= @api_key%>&callback=initMap">
</script>
<div class="container">
  <table class="table">
    <tr>
      <th></th>
      <th></th>
    </tr>
    <tr>
      <td>店舗名</td>
      <td><%= @shop_api.name %></td>
    </tr>
    <tr>
      <td>営業時間</td>
      <td>
        <ul style="list-style:none; margin-left: 0; padding-left: 0;">
          <%@shop_api.opening_hours["weekday_text"].each_with_index do |opening_hour, week|%>
            <%if week != @week%>
              <li><%=opening_hour%></li>
            <%else%>
              <li><%=opening_hour%><span class="label label-info">Today</span></li>
            <%end%>
          <%end%>
        </ul>
      </td>
    </tr>
    <tr>
      <td>ジャンル</td>
      <td>
        <div id="edit_categories"></div>
        <div id="categories">
          <%= render partial: 'categories' %>
        </div>
      </td>
    </tr>
  </table>
</div>
<div class="modal fade" id="registed">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">新しいお店登録完了</h4>
      </div>
      <div class="modal-body">
        <p><%= @shop_api.name %>を新しく登録しました</p>
        <p>このページでお店の画像やジャンルを編集することができます</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

app/views/shops/show.js.erb
$("#now_open_shop").html('<%= j(render :partial => "now_open_shops", :locals => {:shops => @shops, :shops_unknown => @shops_unknown, :week => @week}) %>');
$("#loading").modal('hide');

app/views/shops/show_now_open.js.erb
$("#now_open_shop").html('<%= j(render :partial => "now_open_shops", :locals => {:shops => @shops, :shops_unknown => @shops_unknown, :week => @week}) %>');
$("#loading").modal('hide');
$(function(){
  showShopCandidateLocation();
});

app/views/shops/update_categories.js.erb
$("#categories").show().html('<%= j(render :partial => "categories", :locals => {:categories => @categories, :categories_owned_by_shop => @categories_owned_by_shop}) %>');
$("#edit_categories").empty();